name: dsc_dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10, <3.11
  - pip
  - numpy>=1.24.1, <2
  - pandas>=1.5.2, <2
  - matplotlib>=3.6.2, <4
  # notebook
  - nb_conda>=2.2.1, <3
  - jupyter=1.0.0
  # In general, notebook should be smaller than 7 so that jupyter_contrib_nbextensions and rise can be used
  # Set to 6.5.4 because 6.5.5. is not running, see https://github.com/microsoft/azuredatastudio/issues/24436
  - notebook=6.5.4
  - jupytext>=1.14.4, <2
  - jupyter_contrib_nbextensions=0.7.0
  # good code
  - mypy>=0.991
  - pandas-stubs>=1.5.2  # Required so that type hints for pandas work
  - pre-commit>=3.4.0, <4
  - dvc>=3.21, <4
  - dvc-gdrive>=2.20.0, <3
  - pip:
    - rise  # Dependencies not available on conda-forge
    - -e .
# dev
  # - pyexasol=0.25.1  # don't need this if I don't want to change the data
  - pdoc>=14.1.0, <15
